about:
  description: 'psyplot is an interactive python visualization framework for

    multi-dimensional data. Being easy scriptable, it can also be used through

    a graphical user interface.

    '
  dev_url: https://github.com/Chilipp/psyplot-gui
  doc_url: http://psyplot.readthedocs.io/projects/psyplot-gui
  home: https://github.com/Chilipp/psyplot-gui
  license: GNU General Public License v2 (GPLv2)
  license_family: GPL2
  license_file: LICENSE
  summary: Graphical user interface for the psyplot package
app:
  entry: psyplot
  icon: logo.png
  summary: Psyplot visualization software
  type: desk
package:
  name: psyplot-gui
  version: 1.0.0.dev0
requirements:
  build:
  - python
  - setuptools
  run:
  - python
  - psyplot
  - qtconsole
  - fasteners
  - sphinx
  - sphinx_rtd_theme
source:
  fn: psyplot-gui-1.0.0.dev0.tar.gz
  url: file:///Users/psommer/Documents/myplots-scripts/psyplot-conda/psyplot-gui/dist/psyplot-gui-1.0.0.dev0.tar.gz
test:
  imports:
  - psyplot_gui
  - psyplot_gui.compat
  - psyplot_gui.config
  - psyplot_gui.sphinx_supp
