language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - QT_VERSION=4
  - QT_VERSION=5
matrix:
  exclude:
    - python: "3.4"
      env: QT_VERSION=5
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - 'echo "main.listen_to_port: false" > psyplotguirc.yaml'
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels chilipp
  - conda config --add channels scitools
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - 'ENVKEY=py"${TRAVIS_PYTHON_VERSION}"_qt"${QT_VERSION}"'

  - conda env create -f tests/envs/environment_$ENVKEY.yml
  - source activate psyplot_gui_$ENVKEY
  # remove the psyplot conda package
  - conda remove --force psyplot
  # checkout the current psyplot version via git
  - git clone "https://github.com/Chilipp/psyplot.git" -b $TRAVIS_BRANCH
  - cd psyplot && python setup.py install && cd .. && rm -rf psyplot
  # use the branch from psy-simple
  - git clone "https://github.com/Chilipp/psy-simple.git" -b $TRAVIS_BRANCH || git clone "https://github.com/Chilipp/psy-simple.git"
  - cd psy-simple && python setup.py install && cd .. && rm -rf psy-simple
  # use the branch from psy-maps
  - git clone "https://github.com/Chilipp/psy-maps.git" -b $TRAVIS_BRANCH || git clone "https://github.com/Chilipp/psy-maps.git"
  - cd psy-maps && python setup.py install && cd .. && rm -rf psy-maps
  # install the rest
  - pip install coveralls
  - pip install pytest-xdist
  - python setup.py install
  - conda env export -n psyplot_gui_$ENVKEY

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - coverage run --source=psyplot_gui setup.py pytest

after_success:
  coveralls

after_failure:
  curl -sT "debug_psyplot.log" chunk.io

