environment:

  PYTHON_ARCH: "64"
  PYTHON: "C:\\Python36-conda64"

  matrix:
    - PYTHON_VERSION: "3.5"
      QT_VERSION: "5"
    - PYTHON_VERSION: "3.6"
      QT_VERSION: "5"
os: unstable
install:
  # Install miniconda Python
  - "powershell ./ci/install_python.ps1"
   # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  # use an innocent matplotlibrc
  - copy /y nul matplotlibrc
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - set ENVKEY=py%PYTHON_VERSION%_qt%QT_VERSION%
  - conda env create -f tests/envs/environment_%ENVKEY%.yml
  - activate psyplot_gui_%ENVKEY%
  # use latest development version
  # NOTE: Remove this when psyplot is stable enough
  - git clone "https://github.com/Chilipp/psyplot.git" -b %APPVEYOR_REPO_BRANCH% || git clone "https://github.com/Chilipp/psyplot.git"
  - cd psyplot && python setup.py install && cd ..
  - ps: Remove-Item -Recurse -Force psyplot
  # use the branch from psy-simple
  - git clone "https://github.com/Chilipp/psy-simple.git" -b %APPVEYOR_REPO_BRANCH% || git clone "https://github.com/Chilipp/psy-simple.git"
  - cd psy-simple && python setup.py install && cd ..
  - ps: Remove-Item -Recurse -Force psy-simple
  - pip install coveralls
  - python setup.py install
  # install the test plugin
  - cd tests/test_plugin && python setup.py install && cd ../../
  # install psyplot_gui
  - python setup.py install
  # export the environment for debugging
  - conda env export -n psyplot_gui_%ENVKEY%
  # print versions of all the important requirements
  - psyplot -aV

build: false

test_script:
  - coverage run -a --source=psyplot_gui setup.py test -a "-v"

after_test:
  - coverage report
