package:
  name: psyplot-gui
  version: 1.2.1
app:
  entry: psyplot
  icon: logo.png
  summary: Psyplot visualization software
  type: desk
requirements:
  build:
  - python
  - setuptools
  run:
  - python
  - psyplot
  - qtconsole
  - fasteners
  - sphinx
  - sphinx_rtd_theme
source:
  path: ../..
test:
  imports:
  - psyplot_gui
  - psyplot_gui.compat
  - psyplot_gui.config
  - psyplot_gui.sphinx_supp
about:
  description: 'psyplot is an interactive python visualization framework for
    multi-dimensional data. Being easy scriptable, it can also be used through
    a graphical user interface.'
  dev_url: https://github.com/Chilipp/psyplot-gui
  doc_url: http://psyplot.readthedocs.io/projects/psyplot-gui
  home: https://github.com/Chilipp/psyplot-gui
  license: GNU General Public License v2 (GPLv2)
  license_family: GPL2
  license_file: LICENSE
  summary: Graphical user interface for the psyplot package
