name: psyplot_gui_docs
channels:
    - chilipp/label/dev
    - conda-forge
dependencies:
    - python=3.6
    - psyplot>1.0.1
    - qtconsole
    - ipykernel
    - pexpect
    - pygments
    - pyqt
    - sphinx
    - psy-simple
    - sphinx-argparse
    - pip:
        - fasteners
        - autodocsumm
