name: psyplot_gui_docs
channels:
    - conda-forge
dependencies:
    - python=3.5
    - psyplot
    - qtconsole
    - ipykernel
    - pexpect
    - pygments
    - pyqt
    - sphinx
    - psy-simple
    - pip:
        - sphinx-argparse==0.1.17
        - fasteners
        - autodocsumm
