name: psyplot_gui_docs
channels:
    - chilipp
dependencies:
    - python=3.4
    - psyplot
    - qtconsole
    - ipykernel
    - pexpect
    - pygments
    - pyqt
    - sphinx
    - pip:
        - sphinx-argparse
        - fasteners
        - autodocsumm
